### ISSUE TITLE
Problem with reading vcf

### ISSUE THREAD

**Issue by zd1** [weizhouUMICH/SAIGE#11]
Hi there, 

Thanks for developing this software. I liked your paper and was trying to test it on some of my VCFs. 

I realised that in the second step (SPAtests) it loops through all variants in the input, in my case it's a genotype VCF, conditioning on "isVariant" variable being true
https://github.com/weizhouUMICH/SAIGE/blob/f50adcf3155bac15a80d41b0d8834db4591a4972/R/SAIGE_SPATest.R#L360

which is from here

https://github.com/weizhouUMICH/SAIGE/blob/c65f602eaf3b4fc7b7536dd0bccba75d0e611203/src/SAIGE_readDosage_vcf.cpp#L77

I have variants in my VCF skipped because they are not determined as a variant by the function. It could be that my VCF is not properly formatted. Could you please point me to some directions for the exact criteria that determine whether an entry is a variant? 

Many thanks,
Zhihao

**Comment by weizhouUMICH** [comment]
Hi Zhihao, 
Thank you for trying SAIGE !
SAIGE in the version 0.22 and after uses the savvy library to read in VCF files
https://github.com/statgen/savvy
 
"isVariant" indicates whether the next line in the VCF file is read successfully. For testing genotypes in VCF,  vcfField ="GT" needs to be used.
 If not all but some variants are skipped, it might be because their minor allele count (MAC) is lower than the minMAC, which, by default, is 1. SAIGE calculates MAC using all tested samples.
Thanks,
Wei

**Comment by zd1** [comment]
Hi Wei, 

Thanks very much for your prompt reply. 

I think my VCF conforms with the VCF specs for GT. I can do the following without any warnings
`bcftools query -f '[%GT\n]' test.vcf.gz` 

I did a few tests and realised that actually the chrom argument seems to be mandatory 
https://github.com/weizhouUMICH/SAIGE/blob/2cd03fd4616bae74d3b7a8ed9ab0a69c3a491c14/extdata/cmd.sh#L36

If this argument is removed at above, then I get `isVariant:  FALSE`. 

However, the help message here seems to suggest that in case of chrom not specified, all markers will be tested
https://github.com/weizhouUMICH/SAIGE/blob/2cd03fd4616bae74d3b7a8ed9ab0a69c3a491c14/extdata/step2_SPAtests.R#L31

Thanks,
Zhihao

**Comment by weizhouUMICH** [comment]
Hi Zhihao, 
I see. The help information has not been updated when we start using the savvy library to read in VCF files. This has just been corrected. Thank you for reporting this!!
Thanks,
Wei
