### ISSUE TITLE
Using SAIGE through Slurm job submission to clusters

### ISSUE THREAD

**Issue by xmduumich** [weizhouUMICH/SAIGE#125]
Dear Dr. Zhou,

I've been trying to utilize the Slurm-based HIPAA-aligned HPC cluster called Armis2 and submit SAIGE jobs to it. I'm having trouble figuring out the correct parameters for resources to request of each SAIGE jobs, and having unsuitable parameters would force the job ended with error exit states.  I would love to ask for your insight of SAIGE designing details so that I can figure out the best way to submit jobs through slurm.

1)	step1 (I believe is multi-threaded?)
How many cores can SAIGE effectively use and how much RAM should I assign to each core? Additionally, where are diminishing returns seen when using more cores – that is, is there some number of cores, say “X” where using more than “X” cores does not improve processing speed.  Likewise, is there some amount of memory, say “Y” GB, where additional memory is not used.

2)	step 2 (I believe is single-threaded?)
How much memory should I allocate to each SAIGE job and how to simply estimate the memory required for each job in this use case?  I don’t want to allocate more memory than needed as this increases the cost and the time it takes in the queue. Is there a good way to estimate how much memory would be used based on the chromosome / genotype file size / step1 results / trait type ? I've observed some non-linear changes in terms of memory usage to different chromosome sizes. 

If there are any examples you can point to for me, that would be greatly helpful as well.

Thank you so much for your time and help.

**Comment by weizhouUMICH** [comment]
Dear @xmduumich, 
1. For step 1, we usually use 32 cores for UK Biobank jobs and we have usually seen that the usage of multiple cores is ~90%. When the sample size is ~400k and the number of markers in the plink file is ~93k, the memory usage is ~10Gb, which increases linearly as the sample size and the number of markers in the plink file. 

2. For step 2, it is single-threaded. The memory usage is quite low because markers are read in and tested one by one, so the memory usage has nothing to do with chromosome / genotype file size/trait type. We do read step 1 results (model file .rda) in to memory. When the sample size is ~400k, the memory usage is < 2Gb. 

For more details, you may have a look at the supplementary table 1 in the SAIGE paper. 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6119127/
Best,
Wei

**Comment by weizhouUMICH** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.
Thanks!
Wei

**Comment by JackieKiewa** [comment]
Dear Dr Zhou,
I'm having a lot of trouble running my Step 2 Saige jobs as a pbs job array (22 jobs, one for each chromosome). Half the jobs fail, sometimes immediately, sometimes after a few minutes, with the exit code 271, which I think means that the job has exceeding its resources. I have upped the memory to 70GB and cpu's to 8 with the same results - but you suggest that for Step 2 we need only 1 cpu and  memory use is small, so I feel very confused. I am using UKBiobank data with approximately 200,000 individuals and 8 million SNPs. I have no trouble running Step 1 with 5 cpus and 30GB of memory. 
Here is my error file:

Warning message:
package ‘optparse’ was built under R version 3.6.3
Garbage collection 16 = 9+2+5 (level 2) ...
85.4 Mbytes of cons cells used (64%)
67.2 Mbytes of vectors used (57%)
########################### Job Execution History #############################

JobName:saigeArrayMaleDpn
SessionId:44446
ResourcesRequested:mem=70gb,ncpus=8,place=free,walltime=36:00:00
ResourcesUsed:cpupercent=118,cput=00:01:35,mem=1392600kb,ncpus=8,vmem=2527616kb,walltime=00:01:52

ExitStatus:271
###############################################################################

**Comment by weizhouUMICH** [comment]
Dear Jackie,

It seems the CPU usage of your job is 1.39Gb, so I don't think the job was
stopped because of the memory problem.
Would you mind sharing more details of the failed jobs? The last few lines
of the log file will be useful.

Thanks,
Wei

**Comment by JackieKiewa** [comment]
Thanks so much for your reply - I really think the problem is at our end.
Sometimes the job goes ahead perfectly, other times it crashes, usually
with a different reason - sometimes can't open a file, or some other
problem. Unfortunately with an array it seems that the job error file gets
overwritten by the next file, so it's not always easy to work out why the
last file crashed, if I'm not quick enough to notice before it gets
overwritten.
If I see something that I think may be due to the program I'll get in touch
again, but at the moment I think it's us.
Thanks again,
Jackie
