### ISSUE TITLE
Source code for SAIGE

### ISSUE THREAD

**Issue by wilkerss227** [weizhouUMICH/SAIGE#13]
Hi, 
I'm having a glibc problem with installing SAIGE. 

Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/apps/R/gcc_6.2.0/library/SAIGE/libs/SAIGE.so':
  /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /usr/local/apps/R/gcc_6.2.0/library/SAIGE/libs/SAIGE.so)
Error: loading failed
Execution halted
ERROR: loading fail

Is it possible that the source can be made available in order to compile on our systems.

Sylvia

**Comment by weizhouUMICH** [comment]
This repository (master) contains the source code for v0.25. Could you try R CMD INSTALL SAIGE(folder) to compile?

**Comment by wilkerss227** [comment]
Same results..Our system has glibc 2.11, so it will fail looking for it.

Sylvia

**Comment by wilkerss227** [comment]
The configure script is missing in your src folder. I can't use the
SAIGE.so that's already compiled.

Sylvia

**Comment by weizhouUMICH** [comment]
The source code SAIGE_0.26.tar.gz can be obtained here https://www.dropbox.com/sh/zmlu1llpxd66pjl/AADFqdssvOBjbWZch6Q9zYNaa?dl=0

You can use R CMD INSTALL SAIGE_0.26.tar.gz

**Comment by jinshaw16** [comment]
Dear Wei,

I have the same error as Sylvia after installing from source, which appears to install successfully:

"
R CMD INSTALL ~/software/SAIGE/SAIGE_0.29.2_R_x86_64-pc-linux-gnu.tar.gz 
* installing to library ‘/home/ji3x/anaconda3/envs/py36a/lib/R/library’
* installing *binary* package ‘SAIGE’ ...
* DONE (SAIGE)
"
However, when loading the library in R I get the following error:

"
library(SAIGE)
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/ji3x/anaconda3/envs/py36a/lib/R/library/SAIGE/libs/SAIGE.so':
  /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/ji3x/anaconda3/envs/py36a/lib/R/library/SAIGE/libs/SAIGE.so)
In addition: Warning message:
package ‘SAIGE’ was built under R version 3.4.4 
"

Output from Sys.info() in R:

" 
                             sysname                             
                             "Linux"         
                              release 
      "2.6.32-696.28.1.el6.x86_64" 
                             version                             
"#1 SMP Wed May 9 23:09:02 UTC 2018"           
                             machine                              
                            "x86_64" 
"

I have loaded all the dependencies using anaconda condo-forge channel and am using anaconda's version of R since this is compiled with a more recent version of gcc (required for RcppAramdillo).

Any advice you would be able to provide would be much appreciated.

Best wishes,

Jamie

**Comment by weizhouUMICH** [comment]
Hi Jamie, 
Which version of ubuntu you are using? I used ubuntu 14.04 to compile the package. 
Thanks,
Wei

**Comment by jinshaw16** [comment]
Hi Wei,

Many thanks for getting back to me.

I've tried it on CentOS release 6.8 and also on CentOS release 6.9. 

Is the problem that I need a more recent version of Ubuntu?

Best wishes,

Jamie

**Comment by jinshaw16** [comment]
Thank you for getting back to me, Wei. I will give these a go (or ask the system admin to see if they can help!).

Best wishes,

Jamie

**Comment by xuefenfei712** [comment]
Dear Wei,
Today I used anaconda to install SAIGE, and well installed, but when I start to use R, an error occurred: 
> library("SAIGE")
Error: package or namespace load failed for 釹AIGE?in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/anaconda3/envs/RSAIGE/lib/R/library/SAIGE/libs/SAIGE.so':
  /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /anaconda3/envs/RSAIGE/lib/R/library/SAIGE/libs/SAIGE.so)
I also refer to the posts before, and tried R CMD INSTALL, but no result. For me it is difficult to install GLIBC2.17,   can I used 2.14 instead or any suggestions? 
thankyou!
liu
