### ISSUE TITLE
Calculating GRM using genotyping/exome data? 

### ISSUE THREAD

**Issue by Ojami** [weizhouUMICH/SAIGE#132]
Hi!

I am trying to run SIAGE-GENE for whole exome sequencing (WES) data. I used a set of high quality variants from genotyping array to generate GRM (step 0), which are ~93 k markers used by UK Biobank for estimating kinship coefficients, and you mentioned before: https://www.ncbi.nlm.nih.gov/pubmed/30104761. I use these set of variants for steps 0 and 1, and in step 1 I use WES data.

I am a bit confused in some steps, which I appreciate if you could help me with!

1. I assume that in steps 0 and 1, a bed file containing those 93 k markers and exome data (intersection of 93 k genotyping markers and markers in exome data) should be used for constructing both full and sparse GRM. However, why can't we use the genotyping/imputation (regardless of accuracy of exome data) data (for the same samples used in exome, for instance in a project like UK Biobank) for estimating relatedness coefficients?

2. After calculating GRM (step 0) using these 93 k variants, I used the same plink file for step 1. But, I get an error that there are not enough variants in MAC category of >0.5 <1.5. Is there something wrong with my approach?

Many thanks in advance!
Best/Oveis

**Comment by weizhouUMICH** [comment]
Hi Ojami, 
Actually for step 0 and step 1, the same plink file should be used. This means, step 0 creates a sparse version of the "full" GRM that is used in step 1. The problem is that for gene-based tests, variance ratios are estimated for rare variants and common variants and for each MAC category that is specified, 30 markers will be randomly selected first and increase by 10 until the variance ratio estimation is stable. Therefore, rare variants need to be included in the plink file, although they are not used for GRM, because only markers with MAF >= minMAFforGRM will be used for GRM and the default value is 0.01. 
You may include all rare variants with MAF < 1% and those 93k markers from the plink files provided by the UKBB in your new plink fie for step 0 and step 1. 

Thanks!
Wei
