### ISSUE TITLE
Interpreting variance ratios

### ISSUE THREAD

**Issue by nkgx** [weizhouUMICH/SAIGE#144]
Is there documentation somewhere about how to interpret the values in the `varianceRatio.txt` file? I am looking at a SAIGE analysis of a case/control trait right now where the file says `0.99095788828329`. Does this mean that ratio between the score statistic with the random effect and the one without it is close to one, suggesting that there is almost no adjustment for sample relatedness being made?

Calculating variance ratios for different MAC bins with SAIGE-GENE I see values like this for the same case/control trait:

```
1.00004885922159
(similar values removed)
1.00004758910566
0.993909709532851
```

For a quant trait and roughly the same individuals they look like this:

```
1.01800794207171
(similar values removed)
1.01725348099214
0.896996172311888
```

In general it looks like the value for the last MAC bin is considerably more different from 1 for quant traits than for case/control traits, even on the same individuals. It also looks like the values get further away from 1 for larger numbers of samples.

Is this what you would expect to see? Can you comment on what sort of variance ratios you observed in the published UK Biobank analyses with SAIGE and SAIGE-GENE?

**Comment by weizhouUMICH** [comment]
Hi Nils, 

The variance ratio is used to approximate the score test variance with GRM using the variance  without GRM in SAIGE for single-variant association tests. This approach has been also used in BOLT-LMM and GRAMMAR-Gamma. What you understand is correct, if the variance ratio is very close to 1, usually the estimate for the variance component parameter for GRM is very close to zero. 
The number can be found in the log file, which is the second number in the line starting with "Final :", or it can be found in R
load("model_out.rda") # model_out.rda is output by step 1
modglmm$theta[2]
For UKBB phenotypes, for traits with high heritability, the variance ratio is more different from 1 than for traits with low heritability. 

For SAIGE-GENE, the variance ratio is used to approximate the score test variance with GRM using the variance with a sparse GRM, which is different from SAIGE, because a sparse GRM is used in the denominator. When a lower cutoff for sample relatedness coefficients is used in the sparse GRM, the variance ratio is closer to 1.  Also in SAIGE-GENE, multiple variance ratios are estimated for different MAC categories. If you use the default setting for MAC categories, it is not unusual to see the last one is different from the previous ones as the last one is for more frequent variants with MAC >= 20, while the others are for rarer markers from singletons to variants with MAC < 20. 
In Supplementary Figure 2 of the SAIGE-GENE paper
(https://www.biorxiv.org/content/10.1101/583278v1.supplementary-material?versioned=true)
, you may find plots for the categorical variance ratios in simulation and real-data. 

Thanks! 
Wei
