### ISSUE TITLE
Error in if (AF > 0.5) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by mmyc3** [weizhouUMICH/SAIGE#154]
Hi Wei

Thanks so much for your great software. I am running into the above error when trying to do single variant association analysis. I am using SAIGE_0.36.2 and R/3.6.1 on a remote server. Unfortunately I cannot copy code out of the environment but have attached a screenshot below. 

I had no problem fitting the null LMM in step 1 with my plink file. I am using a VCF file for step 2 with 6661 samples and just running it on 1 chromosome (chr9) to start. The command I am using is:

SPAGMMATtest(vcfFile="./data/chr9.vcf.gz", vcfFileIndex="./data/chr9.vcf.gz.tbi", vcfField="GT", sampleFile="./data/samples.txt", chrom="chr9", minMAC=0.5, minMAF=0.01, GMMATmodelFile="./analysis/x.rda", varianceRatioFile="./analysis/x.varianceRatio.txt", SAIGEOutputFile="./analysis/x.SAIGE.txt", numLinesOutput=2, IsOutputAFinCaseCtrl=TRUE, IsOutoutNinCaseCtrl=TRUE, LOCO=FALSE, IsDropMissingDosages=TRUE)

The AF fields are in the VCF file.

I would appreciate your help on why I am getting this error.

Thanks

Melanie

![Screenshot from 2020-03-03 16-57-37](https://user-images.githubusercontent.com/33218646/75799519-1ba8f780-5d70-11ea-9832-fcf61a059983.png)

**Comment by weizhouUMICH** [comment]
Hi Melanie, 

Happy to help! SAIGE calculates within sample AF from vcf instead of extracting AF from the info column. As it works for previous variants in the vcf, do you notice anything special for the variant that has the error? 
Would it possible that you share an example data set that we can debug? 

Thanks!
Wei

**Comment by mmyc3** [comment]
Hi Wei

Thanks for your swift reply. Unfortunately all my data are within a remote research environment so I cannot export any out. The files are VCFv4.2 - filtered, merged, normalized, left-aligned, split-multiallelics using bcftools/1.9 and annotated with VEP/96. They are generated from whole genome sequencing data and contain 200,000-250,000 variants per chromosome. 

I have now tried with all the chromosomes and get the same error each time, however sometimes it errors before printing out the numPassMarker (see below) and sometimes after 1 or more iterations.  I am not sure how I tell which variant is throwing the error - is it to do with the 2/4/6 etc numbers?

Apologies I cannot give you any example data.

Best wishes

Melanie

![Screenshot from 2020-03-04 13-55-25](https://user-images.githubusercontent.com/33218646/75887033-148df200-5e21-11ea-9202-3a4a40086cbd.png)

**Comment by quinne5** [comment]
Hi , I am getting this same error using the latest version of SAIGE  but only for some chromosomes. I wouldn't even have noticed if i hadn't checked the log files for each as my results files still contain association results for over 200,000 markers. Most chromosomes are completing fine. Is this something to do with my MAF/MAC settings? 

[1] 190000
numPassMarker:  190000
Error in if (AF > 0.5) { : missing value where TRUE/FALSE needed
Calls: SPAGMMATtest
Execution halted

**Comment by weizhouUMICH** [comment]
Hi @mmyc3 and @quinne5, 

I think the error because that for some markers, no samples have non-missing genotypes or dosages in the VCF file. I tried to simulate a marker rs25 in the file with missing genotypes for all samples https://github.com/weizhouUMICH/SAIGE/blob/master/extdata/input/genotype_10markers_triallelic.missing.withVarianceallMissing.vcf
It gives the same error as you showed. I fixed this problem in the new version 0.36.4 by setting the AF to be 0 for these markers. Please give it a try. 
Not sure if it can completely solve the issue in your data set. Sorry for taking so long to get back to you. 

Thanks,
Wei

**Comment by mmyc3** [comment]
Thanks so much Wei. I will try it out and let you know how I get on.

Best wishes

Melanie
________________________________

**Comment by weizhouUMICH** [comment]
Hi @mmyc3, 
Please feel free to re-open this issue if it persists. 

Thanks,
Wei
