### ISSUE TITLE
SAIGE-GENE vs Robust-SKAT 

### ISSUE THREAD

**Issue by Shicheng-Guo** [weizhouUMICH/SAIGE#182]
Dear Dr. Zhou, 

I want to know what's the difference between SAIGE-GENE with the Robust-SKAT method which is published in AJHG 2019. 

https://www.sciencedirect.com/science/article/abs/pii/S0002929719304331?via%3Dihub

Thanks. 

Shicheng

**Comment by weizhouUMICH** [comment]
Dear Shicheng,

SAIGE-GENE uses the same approach to account for unbalanced case-control
ratios for gene-based tests as Robust-SKAT. SAIGE-GENE accounts for sample
relatedness and is feasible for large sample sizes, while Robust-SKAT was
developed for independent samples.

Thanks,
Wei

**Comment by Shicheng-Guo** [comment]
Dear Wei, 

Thanks for the response. Is there any computational time comparison between SAIGE-GENE and Robust-SKAT.  I have used Robust-SKAT for several time while did not try SAIGE-GENE before since the installation of SAIGE-GENE always failed although I have tried with several different ways. 

Thanks.

Shicheng

**Comment by weizhouUMICH** [comment]
Dear Shicheng,

We haven’t compared these two programs for their computation time
empirically, because SAIGE-GENE is for related samples and Robust-SKAT is
for unrelated samples.  SAIGE-GENE fit a logistic mixed model, which takes
more time to fit than a logistic model used by SKAT-Robust.  If your data
set has relateded samples, you will need to use SAIGE-GENE to account for
the sample relatedness.

I’m sorry to hear that you have met problems when install SAIGE and we are
trying our best to make the installation easier. Would you be able to use
the conda environment to compile the program? Or using the docket image is
the most convenient way.

Thanks,
Wei

**Comment by Shicheng-Guo** [comment]
Dear Wei, 

That's fine. It definitely can be solved with more tries.  Can you make a explicit explanation to the `path_to_final_SAIGE_library`.  I want to make sure the install problem is not caused by this command. 

```
  src_branch=master
  repo_src_url=https://github.com/weizhouUMICH/SAIGE
  git clone --depth 1 -b $src_branch $repo_src_url

  R CMD INSTALL --library=**_path_to_final_SAIGE_library_** SAIGE
```

Thanks. 

Shicheng

**Comment by weizhouUMICH** [comment]
Dear Shicheng, 

Than path_to_final_SAIGE_library is a folder where you'd like to install the SAIGE R library. 
If you don't specify this and run 

`  R CMD INSTALL SAIGE`

SAIGE will be installed to the default path of R libraries and in R you can call it with 
` library(SAIGE)`

If you specify the path `R CMD INSTALL --library=**_path_to_final_SAIGE_library_** SAIGE`, then
in R you can call the SAIGE library with 
` library(SAIGE, lib.loc=path_to_final_SAIGE_library)`

Thanks,
Wei

**Comment by Shicheng-Guo** [comment]
Dear Wei, 

Successfully installed and I am not sure what I have changed compared with my previous installation.  Thanks for the helps!!

Shicheng

**Comment by weizhouUMICH** [comment]
No problem. Thanks for the update!
