### ISSUE TITLE
SAIGE Gene-based test error,

### ISSUE THREAD

**Issue by vinodhsri** [weizhouUMICH/SAIGE#184]
![image](https://user-images.githubusercontent.com/65249688/81731150-2c52a980-9454-11ea-8e5f-1ca57d677c4e.png)

**Comment by weizhouUMICH** [comment]
Hi @vinodhsri, 
Thanks for reporting this issue!
The error is because that there is only one marker in the gene and the marker was removed from the test because of a very small variance. I will add a script to check this in the next version. Before that, could you please try remove this gene from test? 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
