### ISSUE TITLE
gene based  tests for all common and rare snp

### ISSUE THREAD

**Issue by Qinqiword** [weizhouUMICH/SAIGE#224]
Hi @weizhouUMICH

I wonder if I use the -- maxMAFforGroupTest=0.5 in the step 2  of gene based tests, does it mean that all common and rare SNPs in a gene will be used for the  gene based tests?

What are the consequences if I do this? Does it make the statistical power  of this gene worse or better ?

Any comments or suggestions would be appreciated.

best,
qinqi

**Comment by weizhouUMICH** [comment]
Hi qinqi, 

Yes if you use -- maxMAFforGroupTest=0.5 in step 2, all common and rare variants in the gene will be included. and association signals, if any, will be likely driven by common variants, although rare variants will have higher weights than common variants in the gene-based tests by default. 

Because single-variant association tests usually have power to identify association signals of common variants but lack of power for rare variants,  gene-based tests can be used to identify association signals of rare variants by grouping them together. We suggest using gene-based tests to test rare variants together for a gene. If a significant signal is identified, conduct a conditional analysis with --condition="nearest significant common variant" to see if the significant signal of rare variants is independent from associations of common variants or not. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei

**Comment by Qinqiword** [comment]
Thanks for your efforts, we will try it !
