### ISSUE TITLE
Installation error: step 3

### ISSUE THREAD

**Issue by ahzhu** [weizhouUMICH/SAIGE#267]
I have been unable to install MetaSKAT (see warning below). I looked at the CRAN page, and the package seems to have been removed. Any help would be appreciated. Thanks!

> install.packages('MetaSKAT')
Warning message:
package ‘MetaSKAT’ is not available (for R version 3.6.1)

**Comment by matuskosut** [comment]
@ahzhu you could use conda approach, where it is still available: https://anaconda.org/conda-forge/r-metaskat

Otherwise [cran memo](https://cran.r-project.org/web/packages/MetaSKAT/index.html) says that it can be obtained in archive, so you could try to install from file (`install.packages(path_to_source, repos = NULL, type="source")`):
> Formerly available versions can be obtained from the archive.
> https://cran.r-project.org/src/contrib/Archive/MetaSKAT/

**Comment by ahzhu** [comment]
Thank you so much, @matuskosut! The conda approach worked perfectly.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
