### ISSUE TITLE
Where is the SAIGE v0.38?

### ISSUE THREAD

**Issue by Esther19960123** [weizhouUMICH/SAIGE#269]
I have read all branches carefully but not found SAIGE version 0.38 which I need. Thanks advanced.

**Comment by matuskosut** [comment]
Hi @Esther19960123  it seems that it was not tagged,

are you sure that you need exactly 0.38? If the reason is this notice [For BGEN input in step 2 with missing dosages, Please use version 0.38](https://github.com/weizhouUMICH/SAIGE#for-bgen-input-in-step-2-with-missing-dosages-please-use-version-038-the-bug-for-bgen-input-with-missing-dosages-was-introducted-in-v0366), I believe that it was fixed in 0.38 and should work in newer versions too. You could try the easy way and install latest saige with conda and test it out:

```
conda install -c bioconda r-saige
```

if you really need 0.38 you should try to look in commits https://github.com/weizhouUMICH/SAIGE/commits/master

**Comment by Esther19960123** [comment]
> Hi @Esther19960123 it seems that it was not tagged,
> 
> are you sure that you need exactly 0.38? If the reason is this notice [For BGEN input in step 2 with missing dosages, Please use version 0.38](https://github.com/weizhouUMICH/SAIGE#for-bgen-input-in-step-2-with-missing-dosages-please-use-version-038-the-bug-for-bgen-input-with-missing-dosages-was-introducted-in-v0366), I believe that it was fixed in 0.38 and should work in newer versions too. You could try the easy way and install latest saige with conda and test it out:
> 
> ```
> conda install -c bioconda r-saige
> ```
> 
> if you really need 0.38 you should try to look in commits https://github.com/weizhouUMICH/SAIGE/commits/master

OK, get it! ~.~

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
