### ISSUE TITLE
Install fails with "Error in getOctD(x, offset, len) : invalid octal digit"

### ISSUE THREAD

**Issue by jet456** [weizhouUMICH/SAIGE#34]
Hi,

Trying to install this package. It fails with the exact same error on CentOS 6.9 (R 3.5.0, also tried R 3.4.0, R 3.3.1) and Ubuntu 14.04 (tried R 3.5.0).

The output:

buildhost<14:03:05> R CMD INSTALL SAIGE_0.29.1_R_x86_64-pc-linux-gnu.tar.gz
Error in getOctD(x, offset, len) : invalid octal digit
buildhost<14:03:09>

Thanks!

**Comment by rkarlssonlinner** [comment]
Hi,

I get the same error on my Mac and on two different servers running a different version of Linux. I have tried all three versions of .tar.gz. Any updates on this issue?

**Comment by jet456** [comment]
I haven't found a solution to this either (though my group and I abandoned the project a few months ago).

**Comment by rkarlssonlinner** [comment]
I may have found a solution. Instead of downloading the .tar.gz by right-clicking in the repository, I instead downloaded the entire repository as .zip. Once unzipped, the .tar.gz are proper and can be installed. I noticed that right-clicking and downloading those separately saves them as:

$ file SAIGE_0.29.4_R_x86_64-pc-linux-gnu.tar.gz
SAIGE_0.29.4_R_x86_64-pc-linux-gnu.tar.gz: HTML document text, UTF-8 Unicode text, with very long lines

instead of the proper format:

$ file SAIGE_0.29.4.2_R_x86_64-pc-linux-gnu.tar.gz
SAIGE_0.29.4.2_R_x86_64-pc-linux-gnu.tar.gz: gzip compressed data, from Unix

**Comment by jet456** [comment]
Interesting -- I had tried that same thing several months back and had gotten the same error (invalid octal digit). I tried it again this time and while the package installed, I got the error below when trying to load it. Our system currently has R 3.5.0, plus GCC installed to a non-standard location (we have a compute cluster). 

```
> library(SAIGE)
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/apps/R-3.5.0/lib64/R/library/SAIGE/libs/SAIGE.so':
  /apps/gcc-4.8.5/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /apps/R-3.5.0/lib64/R/library/SAIGE/libs/SAIGE.so)
In addition: Warning message:
package ‘SAIGE’ was built under R version 3.5.1
```

**Comment by jet456** [comment]
I noticed there was an update to this package 18 days ago -- noting that I tried to install the update and got the same error as before "invalid octal digit".
