### ISSUE TITLE
Same values in pvalue and pvalue.na fields

### ISSUE THREAD

**Issue by aritra90** [weizhouUMICH/SAIGE#376]
Hi, 

I am running single-variant association tests using SAIGE and getting same values for the pvalue and pvalue.na (with and without SPA) fields. I was wondering when would this happen and is it a common phenomenon or am I missing something? 

Thanks

**Comment by weizhouUMICH** [comment]
Hi @aritra90, 

Sorry for my late reply.
This is because by default, SPA only applies to markers with p-value (under the normal approximation) < 0.05. 

We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/

The program will be maintained by multiple SAIGE developers there. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
