### ISSUE TITLE
including rare variants in GRM decrease statistical power to identify novel targets?

### ISSUE THREAD

**Issue by Shicheng-Guo** [weizhouUMICH/SAIGE#399]
Dear Zhou, 

I am wondering did we evaluate whether including rare variants in GRM will decrease statistical power to identify novel targets?

Thanks. 

Shicheng

**Comment by weizhouUMICH** [comment]
Hi Shicheng, 

We didn't evaluated the performance of including rare variants in GRM. We recommend using common variants to construct GRM, because the sample relatedness coefficient will be largely driven by rare variants if they are included. 

We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. I've previously successfully used the docker image for version 0.99.3 on both Google cloud and DNAnexus. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
