### ISSUE TITLE
Warning: no sample level data available

### ISSUE THREAD

**Issue by michelemarongiu79** [weizhouUMICH/SAIGE#402]
Hi everynone,

I'm running SAIGE 0.44.2, STEP2 with step2_SPAtests.R.
this is my bash file:

chr=$1
trait=$2

Rscript step2_SPAtests.R	\
--vcfFile=/myvcf/geno.chr$chr.vcf.gz \
--vcfFileIndex=/myvcf/geno.chr$chr.vcf.gz.tbi \
--vcfField=DS \
--chrom=$chr \
--minMAC=1 \
--GMMATmodelFile=$PWD/GRM_$trait.rda \
--varianceRatioFile=$PWD/GRM_$trait.varianceRatio.txt \
--SAIGEOutputFile=$PWD/GRM_$trait.$chr.SAIGE.vcf.genotype.txt \
--numLinesOutput=2 \
--LOCO=TRUE

I paste the last lines with the error:

It is a quantitative trait
isCondition is  FALSE 
Analysis started at  1645531870 Seconds
Warning: no sample level data available
Error in if (markerInfo >= 0 & markerInfo <= 1) { : 
  argument is of length zero
Calls: SPAGMMATtest
Execution halted

I think it is a mistake on the samples, 
can anyone help me?

Thank you all
M.

**Comment by weizhouUMICH** [comment]
Hi @michelemarongiu79, 

Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/

The program will be maintained by multiple SAIGE developers there. 
Note that the csi instead of tbi index file is used for VCF input. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
