### ISSUE TITLE
Possible to speed up using speedglm instead of glm?

### ISSUE THREAD

**Issue by carbocation** [weizhouUMICH/SAIGE#42]
For, e.g., logistic regression on UK Biobank sized data sets with many covariates (e.g., all 40 PCs), speedglm is much faster to compute than glm. (In my experience, the speedup is at least a few orders of magnitude.) Because of the symlink issue in #41 , I don't think I can try to rebuild this, but I wonder if you'd consider testing a build using speedglm to see if it suits your needs.

**Comment by weizhouUMICH** [comment]
Thank you for letting me know! 
In order to avoid the symlink, you may install the savvy library in your local SAIGE folder by going to the SAIGE/thirdparty

rm -r cget
cget install  -DCMAKE_CXX_FLAGS="-fPIC"  -DCMAKE_C_FLAGS="-fPIC” statgen/savvy

If this can't solve your problem, please let me know. I will replace glm with speedglm for you.

**Comment by weizhouUMICH** [comment]
I’m closing this issue because it has been inactive for a few months. 
Please reopen if you still encounter this issue. 
Thank you!
