### ISSUE TITLE
running SAIGE per chromosome

### ISSUE THREAD

**Issue by ruthchia** [weizhouUMICH/SAIGE#52]
Hi, I am wondering if it would be possible to run SAIGE per chromosome when LOCO is set to FALSE?
I am asking because my  genotype and imputed dosage files are already broken down  per chromosome and to have to merge them seems a little cumbersome and the files are huge. 
Can you please clarify?
Thanks!
Ruth

**Comment by weizhouUMICH** [comment]
Hi Ruth,

For step1, the plink file is used for constructing the genetic relationship
matrix. It is ok to specify a plink file with one chromosome if it fits
your research interest, but usually we recommend using a genome-wide plink
file, so the sample relatedness can be well captured. BTW, this plink file
usually contains genotyped variants.

For step 2, you may definitely specify files for dosages to test by
chromosome.

Thanks,
Wei

**Comment by ruthchia** [comment]
Hi Wei,
Thanks for the clarification!
Appreciate it!
Ruth

**Comment by jjfarrell** [comment]
For the plink genotype file used for Step 1, is there a standard preparation recommended?  For example, is LD pruning and a MAF cutoff recommended?

**Comment by weizhouUMICH** [comment]
Hi @jjfarrell, 

Sorry for my late reply!!
We usually use LD-pruned plink genotype file for GRM with common markers. Since version 0.36.1 , an option minMAFforGRM is added to specify a min MAF cutoff for markers used for GRM from the plink file. The default value is minMAFforGRM = 0.01

Please reopen if you still encounter this issue. 
Thanks!
Wei
