### ISSUE TITLE
Unable to run SAIGE with BGEN files

### ISSUE THREAD

**Issue by joshbTerps** [weizhouUMICH/SAIGE#6]
Hi Wei, 

I've been unable to get SAIGE to run properly with BGEN files (version 1.2 with 8 bit compression).
I receive the following error:

Error in getDosage_bgen_noquery() : BGenError
Calls: SPAGMMATtest -> getDosage_bgen_noquery -> .Call
Execution halted

Running SAIGE with BGEN does produce a SAIGE.txt output file, but the p-values of positive controls in the SAIGE.txt file do not align at all with results from a logistic model. Do you know what might be causing this?

Thanks for any help,
Josh

**Comment by weizhouUMICH** [comment]
Hi Josh, 
Sorry for missing your issue for so long. 
1. I'm trying to add some bgen examples to the library in the next one or two days. Hopefully, by then you can run the examples to see whether the library works well with bgen examples in your computer. We will see whether the error is because the library is not correctly installed or the bgen file you used has some issues. 
2. When the case-control ratio is unbalanced, SAIGE corrects for the inflation that you may get from a logistic model while taking the sample relatedness into account. 

Thanks,
Wei

**Comment by joshbTerps** [comment]
Thanks for addressing it. I am working on AWS so perhaps some issues with C++ libraries. 
I can tell you it is not a bgen issue as I am able to use the same files with plink and bolt. I understand your second point (one of the reasons I want to use SAIGE), but even so, the association signal for the positive control SNPs in my dataset should be off the charts significant. 

Thanks again,
Josh

**Comment by weizhouUMICH** [comment]
An example bgen file has now been uploaded to the extdata folder.

One possible reason for the issue that the association results do not match the expectation is that the number or order of the samples specified in the sample file does not match those in the actual bgen file. 
Could you please double check this? 

Thanks,
Wei

**Comment by joshbTerps** [comment]
Hi Wei, thanks for uploading the example bgen. It indeed was an issue with the sample files -- the sample file required for SAIGE is not the same format as the sample file that typically corresponds with a bgen file. 

For clarity, can you please explain what the p.value.NA column is? 

Thanks,
Josh

**Comment by weizhouUMICH** [comment]
Hi Josh,

Thank you for letting me know!
The p.value.NA column is for p values from score tests based on logistic
mixed models, in which the saddlepoint approximation (SPA) has not been
used to account for case-control imbalance.

Thanks,
Wei







Wei Zhou
Ph.D. Candidate
Bioinformatic Program
University of Michigan-Ann Arbor

**Comment by joshbTerps** [comment]
Got it. Thanks so much!
