### ISSUE TITLE
library error 

### ISSUE THREAD

**Issue by wuyeda** [weizhouUMICH/SAIGE#8]
I have installed the SAIGE package in R successfully. However, when I library the package, the error shows like this:

Error in dyn.load(file, DLLpath = DLLpath, ...) :
unable to load shared object '/home/yeda.wu/R/x86_64-pc-linux-gnu-library/3.4/SAIGE/libs/SAIGE.so':
liblapack.so.3: cannot open shared object file: No such file or directory
In addition: Warning message:
package 'SAIGE' was built under R version 3.4.3
Error: package or namespace load failed for ‘SAIGE'

I am not sure what’s going on here. Could you please give me some advice?

Thanks in advance.

**Comment by weizhouUMICH** [comment]
I think the error may be due to the version of lapack linker used by R. It may be because that the linker used by your R version is -lRlapack instead of -llapack.
You may check using

R CMD config LAPACK_LIBS

Thanks,
Wei

**Comment by wuyeda** [comment]
Hi Wei,
Thank you for your suggestion. I checked the linker used by R version and it shows as 

-L/opt/Modules/R/3.4.1/lib64/R/lib -lRlapack

Could you please give me some advice on how to fix the problem.

Thank you in advance.

Best wishes,
Yeda

**Comment by kjacks56** [comment]
Hi @weizhouUMICH, 

I am having a similar issue to Yeda. I have successfully installed the package, but when I attempt to load it into R, I get the following error: 

**Error: package ‘SAIGE’ was built for x86_64-pc-linux-gnu**

I have checked that my version of R is using the -lRlapack linker instead of -llapack. 
I am running a Mac OS operating system and noticed that the current gcc target for my OS is x86_64-apple-darwin16.7.0. 

From what I can find online, it seems that I can build a gcc cross-compiler for my OS, but I am hesitant to do this. Will updating my R version and the linker that it uses solve this problem? 


Thank you!
Kayla

**Comment by kjacks56** [comment]
I was able to solve the library error by installing an Ubuntu Virtual Machine on my mac using Oracle VirtualBox. The package installed and loaded into R without issue.

**Comment by weizhouUMICH** [comment]
Thank you! @kjacks56 
@wuyeda 
I have found this thread that discussed the same problem and provideed two possible solutions
https://forums.aws.amazon.com/thread.jspa?threadID=165667

Both of them worked for me

1. symbolically-link the system-level libraries
```
sudo ln -sf  /usr/lib64/libblas.so /usr/lib64/R/lib/libRblas.so
sudo ln -sf  /usr/lib64/liblapack.so /usr/lib64/R/lib/libRlapack.so
```

2. edit the /usr/lib64/R/etc/Makeconf entries to:
```
BLAS_LIBS = -lblas
LAPACK_LIBS = -llapack
```

Thanks!
Wei

**Comment by ffang8** [comment]
I got the same issue here, and I do not have the root permission in the system to do either work-around way. Is there any other way to work out this lapack linker problem? Thanks a lot.

**Comment by weizhouUMICH** [comment]
Hi @ffang8, 

Now we have 5 different approaches to install the package. docker image or the conda env file can be used if you don't have a root permission. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#installing-saige
